name: Prereleased



on:
  release:
    types:
    - prereleased



env:
  GHCR_REGISTRY: ghcr.io/${{ github.repository_owner }}
  GHCR_USERNAME: ${{ github.repository_owner }}
  GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

  DOCKER_REPOSITORY: backoffice



jobs:
  cancel_previous:
    name: 'Cancel Previous Runs'
    runs-on: ubuntu-20.04
    timeout-minutes: 3

    steps:
      - uses: ydataai/cancel-workflow-action@0.7.0-fix
        with:
          ignore_sha: true
          access_token: ${{ secrets.ACCESS_TOKEN }}


  prepare:
    name: Prepare
    runs-on: ubuntu-20.04

    needs:
    - cancel_previous

    outputs:
      version: ${{ steps.version.outputs.value }}

    steps:
    - name: Version
      id: version
      run: echo ::set-output name=value::${GITHUB_REF#refs/*/}


  build:
    name: Build
    runs-on: ubuntu-20.04

    needs:
    - prepare

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      id: cache
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}-${{ github.workspace }}
        restore-keys: ${{ runner.os }}-spm-${{ hashFiles('Package.resolved') }}-${{ github.workspace }}

    - name: Login to GitHub Registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.GHCR_REGISTRY }}
        username: ${{ env.GHCR_USERNAME }}
        password: ${{ env.GHCR_PASSWORD }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      env:
        DOCKER_IMAGE_TAG: ${{ env.GHCR_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ needs.prepare.outputs.version }}
      with:
        push: true
        tags: ${{ env.DOCKER_IMAGE_TAG }}
        secrets: |
          GIT_AUTH_TOKEN=${{ secrets.GHCR_TOKEN }}
